name: Deploy Dev User Site

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: 'YY.MM.DD.HH.mm'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build Project
        env:
          VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}
        run: pnpm build --filter frontend
      - name: Deploy user site
        run: aws s3 sync ./apps/frontend/dist s3://${{ secrets.S3_BUCKET }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
